const A=document.querySelector('#app');
const food=[['Eggs',15,'dozen'],['Muffins',6,'dozen'],['Granola Bars',6,'boxes','Please consider gluten-free options.'],['Bananas',6,'bunches'],['Variety Packs of Chips',20,'packs'],['Chili',4,'crock pots'],['Full-Sized Candy Bars',10,'boxes'],['Cookies',8,'dozen'],['Hot Dog Buns',30,'packages']];
const equip=[['Propane Tanks',5,'tanks','Please label the tank with your name. Tanks can be picked up Sunday afternoon.'],['6-Foot Folding Tables',10,'tables','Please label the table with your name. Tables can be picked up Sunday afternoon.']];
const roles={Concessions:{icon:'🥤',desc:'Get our delicious treats into the hands of hungry spectators! Ensure coffee and hot water for cocoa are always ready.',sat:[['8:00–10:00 AM',3,'2 volunteers should arrive at 7:30 AM to help with opening setup.'],['10:00 AM–12:00 PM',2],['12:00–2:00 PM',2],['2:00–4:00 PM',2],['4:00–5:00 PM',3,'Closing concessions: sell remaining prepared food and help with breakdown.']],sun:[['8:00–10:00 AM',3,'Includes opening/setup.'],['10:00 AM–12:00 PM',2],['12:00–2:00 PM',2],['1:00–2:00 PM',3,'Closing concessions: sell remaining prepared food and handle breakdown.']]},Grill:{icon:'🔥',desc:'Grill up our breakfast sandwiches and hot dogs during the day! Help out with concession sales during slower cooking times.',sat:[['8:00–10:00 AM',1],['10:00 AM–12:00 PM',1],['12:00–2:00 PM',1],['2:00–4:00 PM',1]],sun:[['8:00–10:00 AM',1],['10:00 AM–12:00 PM',1],['12:00–2:00 PM',1,'Final grill shift; avoid cooking excess near closing.']]},Facilities:{icon:'🧹',desc:'Check for overflowing trash cans, ensure toilets are stocked, and alert us about any parking violations. Assist with concessions once rounds are completed.',sat:[['9:00–11:00 AM',1],['11:00 AM–1:00 PM',1],['1:00–3:00 PM',1],['3:00–5:00 PM',1]],sun:[['9:00–11:00 AM',1],['11:00 AM–1:00 PM',1]]}};
const ball={sat:[['8:30–9:50 AM',2,'8:30 & 9:10 games'],['9:50–11:10 AM',2,'9:50 & 10:30 games'],['11:10 AM–12:30 PM',2,'11:10 & 11:50 games'],['12:30–1:50 PM',2,'12:30 & 1:10 games'],['1:50–3:10 PM',2,'1:50 & 2:30 games'],['3:10–4:30 PM',2,'3:10 & 3:50 games'],['4:30–5:10 PM',2,'4:30 game']],sun:[['9:00–10:20 AM',2,'9:00 & 9:40 games'],['10:30–11:50 AM',2,'10:30 & 11:10 championship games']]};
let state={open:true,signups:[],shopping:null};try{const saved=localStorage.getItem('wmsState');if(saved){const parsed=JSON.parse(saved);if(parsed&&Array.isArray(parsed.signups))state=Object.assign(state,parsed)}}catch(e){try{localStorage.removeItem('wmsState')}catch(_){} }let view='home',pick=null;const save=()=>localStorage.setItem('wmsState',JSON.stringify(state));const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const count=id=>state.signups.filter(x=>x.id===id).reduce((a,x)=>a+(x.qty||1),0);const slots=(id,total)=>Math.max(0,total-count(id));
function frame(body){A.innerHTML=`<main class="shell">${body}<div class="footer">Westmoreland Bulldogs • October 24–25, 2026</div></main>`}
function home(){frame(`<div class="hero"><div class="eyebrow">WESTMORELAND BULLDOGS</div><h1>47th Annual Westmoreland Middle School Soccer Tournament</h1><p>October 24–25, 2026</p></div>${!state.open?`<div class="card closed"><div class="title">Sign-ups are now closed</div><div class="sub">Thank you for supporting the tournament! Existing commitments are still available under My Sign-Ups.</div></div>`:''}<div class="card money"><div class="title">💵 Monetary Donations</div><div class="sub">Send cash or check to school in a sealed envelope marked “Soccer Tournament Donation”. Checks can be made out to Westmoreland PTA.</div></div>${nav('🍎','Food Donations','Help stock the tournament concession stand','food')}${nav('⚽','Equipment','Propane tanks and folding tables','equipment')}${nav('🙋','Concessions Volunteers','Setup • Concessions • Grill • Facilities','vol')}${nav('⚽','Ball Kids','Two fields • two consecutive games per shift','ball')}${nav('📋','My Sign-Ups','View, edit, or cancel commitments on this device','mine')}<button class="back" onclick="go('admin')">Organizer Dashboard →</button>`)}
function nav(i,t,s,v){return `<button class="card nav" onclick="go('${v}')"><span class="icon">${i}</span><span class="grow"><span class="title">${t}</span><span class="sub">${s}</span></span><b>›</b></button>`}
function top(title,sub=''){return `<button class="back" onclick="go('home')">‹ Home</button><div class="heading">${title}</div>${sub?`<div class="sub">${sub}</div>`:''}`}
function donation(kind,data){frame(top(kind==='food'?'🍎 Food Donations':'⚽ Equipment')+data.map((x,i)=>{let id=`${kind}-${i}`,claimed=count(id),remain=Math.max(0,x[1]-claimed);return `<div class="card"><div class="title">${esc(x[0])}</div><div class="sub"><b>${remain} ${esc(x[2])} remaining</b> of ${x[1]}</div><div class="progress"><i style="width:${Math.min(100,claimed/x[1]*100)}%"></i></div>${x[3]?`<div class="note">${esc(x[3])}</div>`:''}<div class="actions"><button class="btn" ${!state.open||!remain?'disabled':''} onclick='signup(${JSON.stringify({id,label:x[0],total:x[1],unit:x[2],type:kind})})'>${remain?'Sign Up':'Filled'}</button></div></div>`}).join(''))}
function volunteers(){frame(top('🙋 Concessions Volunteers','Choose the job you’d like to help with, then select a shift.')+`<div class="day">Friday, October 23 • 4:00–6:00 PM</div>${shiftCard('Friday Parking & Signage Setup — 4:00–6:00 PM','friday-parking',3,'🚗 Parking & Signage Setup')}${shiftCard('Friday Concession Stand Setup — 4:00–6:00 PM','friday-concession',3,'🥤 Concession Stand Setup')}<div class="day">Weekend Volunteer Roles</div>${Object.entries(roles).map(([k,r])=>nav(r.icon,k,'Tap to see responsibilities and available shifts',`role:${k}`)).join('')}`)}
function shiftCard(label,id,total,title=label,note=''){let left=slots(id,total);return `<div class="card"><div class="title">${title}</div><div class="sub">${left} of ${total} spots remaining</div>${note?`<div class="note">${note}</div>`:''}<button class="btn" ${!state.open||!left?'disabled':''} onclick='signup(${JSON.stringify({id,label,total,type:'shift'})})'>${left?'Sign Up':'Filled'}</button></div>`}
function rolePage(k){let r=roles[k];frame(`<button class="back" onclick="go('vol')">‹ Concessions Volunteers</button><div class="heading">${r.icon} ${k}</div><div class="note">${r.desc}</div>${roleDay(k,'Saturday, October 24',r.sat,'sat')}${roleDay(k,'Sunday, October 25',r.sun,'sun')}`)}
function roleDay(k,day,arr,d){return `<div class="day">${day}</div><div class="card">${arr.map((x,i)=>{let id=`role-${k}-${d}-${i}`,left=slots(id,x[1]);return `<div class="shift"><div class="grow"><b>${x[0]}</b><div class="sub">${left} of ${x[1]} ${x[1]===1?'spot':'spots'} remaining${x[2]?` • ${x[2]}`:''}</div></div><button class="btn" ${!state.open||!left?'disabled':''} onclick='signup(${JSON.stringify({id,label:`${k} — ${day} — ${x[0]}`,total:x[1],type:'shift'})})'>Sign Up</button></div>`}).join('')}</div>`}
function ballKids(){frame(top('⚽ Ball Kids','Each shift covers two consecutive games. Two Ball Kids are needed per shift—one for each field. Field assignments can be made when volunteers arrive.')+ballDay('Saturday, October 24',ball.sat,'sat')+ballDay('Sunday, October 25',ball.sun,'sun'))}
function ballDay(day,arr,d){return `<div class="day">${day}</div><div class="card">${arr.map((x,i)=>{let id=`ball-${d}-${i}`,left=slots(id,x[1]);return `<div class="shift"><div class="grow"><b>${x[0]}</b><div class="sub">${x[2]} • ${left} of 2 spots remaining</div></div><button class="btn" ${!state.open||!left?'disabled':''} onclick='signup(${JSON.stringify({id,label:`Ball Kids — ${day} — ${x[0]}`,total:2,type:'shift'})})'>Sign Up</button></div>`}).join('')}</div>`}
function signup(o){pick=o;view='form';let max=o.type==='food'||o.type==='equipment'?Math.max(1,o.total-count(o.id)):1;frame(`<button class="back" onclick="go('${o.type==='food'?'food':o.type==='equipment'?'equipment':'home'}')">‹ Back</button><div class="heading">Sign Up</div><div class="card"><div class="title">${esc(o.label)}</div><form onsubmit="confirmSignup(event)">${max>1?`<label>Quantity</label><select id="qty">${Array.from({length:max},(_,i)=>`<option>${i+1}</option>`).join('')}</select>`:''}<label>Name</label><input id="name" required autocomplete="name"><label>Email or phone</label><input id="contact" required autocomplete="email"><div class="sub">Used privately to identify your signup and help recover it later.</div><button class="btn" style="width:100%;margin-top:16px">Confirm Sign-Up</button></form></div>`)}
function confirmSignup(e){e.preventDefault();let qtyEl=document.querySelector('#qty');let q=+(qtyEl?qtyEl.value:1);state.signups.push({...pick,qty:q,name:document.querySelector('#name').value.trim(),contact:document.querySelector('#contact').value.trim(),key:Date.now()});save();go('mine')}
function mine(){frame(top('📋 My Sign-Ups','This prototype automatically remembers sign-ups made on this device.')+(state.signups.length?state.signups.map(x=>`<div class="card"><div class="title">${esc(x.label)}</div><div class="sub">${x.qty>1?`${x.qty} ${esc(x.unit||'items')} • `:''}${esc(x.name)}</div><div class="actions"><button class="btn danger" onclick="cancel(${x.key})">Cancel</button></div></div>`).join(''):`<div class="card"><div class="sub">No sign-ups have been made on this device yet.</div></div>`)+`<div class="note"><b>Different device?</b><br>In the live version, Find My Sign-Ups will verify the email address or phone number used during signup and then load those commitments. Public name-only searching will not expose private sign-ups.</div>`)}
function cancel(k){if(confirm('Cancel this sign-up?')){state.signups=state.signups.filter(x=>x.key!==k);save();mine()}}
function admin(){let needs=shoppingRows();frame(`<button class="back" onclick="go('home')">‹ Public Site</button><div class="heading">Organizer Dashboard</div><div class="card adminbar"><div><div class="title">Public Sign-Ups</div><div class="sub">${state.open?'People can currently make new commitments.':'New commitments are currently closed.'}</div></div><label class="toggle"><input type="checkbox" ${state.open?'checked':''} onchange="toggleOpen(this.checked)">${state.open?'OPEN':'CLOSED'}</label></div><div class="card attention"><div class="title">Needs Attention</div><div class="sub">${needs.length?`${needs.length} donation item${needs.length===1?'':'s'} still need to be filled.`:'Food and equipment donation needs are fully claimed.'}</div></div>${nav('🛒','Shopping List',state.shopping?'Frozen shopping list created when sign-ups were closed.':'Create a list from remaining donation quantities','shopping')}${nav('👥','All Sign-Ups',`${state.signups.length} current commitment${state.signups.length===1?'':'s'}`,'all')}<div class="card"><div class="title">Tournament Settings</div><div class="sub">The production version will include tournament name/dates, section publishing, item and shift editing, archiving, and Create Next Tournament.</div></div>`)}
function toggleOpen(v){if(!v&&state.open&&!state.shopping)state.shopping=shoppingRows().map(x=>({...x,done:false}));state.open=v;save();admin()}
function shoppingRows(){return [...food.map((x,i)=>({name:x[0],qty:Math.max(0,x[1]-count(`food-${i}`)),unit:x[2]})),...equip.map((x,i)=>({name:x[0],qty:Math.max(0,x[1]-count(`equipment-${i}`)),unit:x[2]}))].filter(x=>x.qty>0)}
function shopping(){let rows=state.shopping||shoppingRows().map(x=>({...x,done:false}));frame(`<button class="back" onclick="go('admin')">‹ Organizer Dashboard</button><div class="heading">🛒 Shopping List</div><div class="sub">${state.shopping?'This list was frozen when public sign-ups were closed.':'Live preview based on what is still needed right now.'}</div><div class="card">${rows.length?rows.map((x,i)=>`<label class="check"><input type="checkbox" ${x.done?'checked':''} onchange="shopCheck(${i},this.checked)" ${state.shopping?'':'disabled'}><span><b>${x.qty} ${esc(x.unit)} ${esc(x.name)}</b></span></label>`).join(''):`<div class="sub">Nothing left to purchase.</div>`}</div>`)}
function shopCheck(i,v){if(state.shopping){state.shopping[i].done=v;save()}}
function all(){const rows=state.signups.length?state.signups.map(x=>`<div class="card"><div class="title">${esc(x.label)}</div><div class="sub">${esc(x.name)} • ${esc(x.contact)}${x.qty>1?` • Qty ${x.qty}`:''}</div><button class="btn danger" onclick="cancelAdmin(${x.key})">Remove</button></div>`).join(''):`<div class="card"><div class="sub">No sign-ups yet.</div></div>`;frame(`<button class="back" onclick="go('admin')">‹ Organizer Dashboard</button><div class="heading">👥 All Sign-Ups</div>${rows}`)}
function cancelAdmin(k){if(confirm('Remove this commitment?')){state.signups=state.signups.filter(x=>x.key!==k);save();all()}}
function go(v){view=v;if(v==='home')home();else if(v==='food')donation('food',food);else if(v==='equipment')donation('equipment',equip);else if(v==='vol')volunteers();else if(v==='ball')ballKids();else if(v==='mine')mine();else if(v==='admin')admin();else if(v==='shopping')shopping();else if(v==='all')all();else if(v.startsWith('role:'))rolePage(v.slice(5));scrollTo(0,0)}
window.go=go;window.signup=signup;window.confirmSignup=confirmSignup;window.cancel=cancel;window.toggleOpen=toggleOpen;window.shopCheck=shopCheck;window.cancelAdmin=cancelAdmin;home();
